const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('dist/index.html','utf8');
const js=fs.readFileSync('dist/app.js','utf8');
const css=fs.readFileSync('dist/styles.css','utf8');
const requiredIds=['calendar','agenda','eventForm','eventType','eventName','eventSystem','startDate','endDate','hoursGroup','startTime','endTime','talentInput','executiveInput','availabilityGroup','detailModal','confirmModal','filterSystem','filterTalent','filterSpecialDays'];
requiredIds.forEach(id=>assert(html.includes(`id="${id}"`),`Falta #${id}`));
assert(js.includes('function jsonpRequest'),'La comunicación debe tener transporte JSONP resistente a CORS');
assert(js.includes("action:'mutate'"),'Las mutaciones deben usar el transporte resistente de Apps Script');
['create','update','delete'].forEach(action=>assert(js.includes(`action:'${action}'`),`Falta CRUD ${action}`));
assert(js.includes('b.innerHTML=`${esc(e.Nombre)}${isCommercializable(e)'),'El nombre debe mostrarse en cada día multidía');
assert(js.includes("specialDays:'__holidays'"),'Solo festivos debe ser inicial');
assert(js.includes("s==='__all'"),'Debe existir Todas para fechas especiales');
assert(js.includes("norm(x.Tipo)==='festivo'"),'Festivo debe filtrarse exactamente');
assert(js.includes('eventRanges:indexByRange(events)'),'Los eventos multidía deben indexarse por rango');
assert(js.includes("apiGet('bootstrap')")||js.includes("megaMode?'megabootstrap':'bootstrap'"),'Debe usarse bootstrap normal y MEGA de forma compatible');
assert(js.includes("apiGet('version')"),'Debe usarse el endpoint ligero de versión');
assert(js.includes("url.searchParams.set('callback',callback)"),'Las lecturas deben enviar callback JSONP');
assert(js.includes('setInterval(checkVersion,60000)'),'La versión debe comprobarse cada 60 segundos');
assert(js.includes("window.addEventListener('focus',checkVersion)"),'Debe sincronizar al recuperar foco');
assert(js.includes("params.get('edit')"),'Los modos deben ser genéricos por query parameter');
assert(js.includes("if(!mode)return"),'La vista pública no puede abrir CRUD');
assert(js.includes("state.selectedDay=null"),'Volver a calendario debe limpiar el día');
assert(js.includes("Talentos:[...state.formTalents]")&&js.includes("Ejecutivos:[...state.formExecutives]"),'Talentos y ejecutivos deben enviarse');
assert(js.includes("if(!d.Sistema&&!$('#eventId').value)"),'Sistema debe ser obligatorio solo para nuevos eventos');
assert(js.includes("if(!yes){$('#startTime').value='';$('#endTime').value=''}"),'Desactivar horas debe limpiar valores');
assert(js.includes("if(!yes)$$('input[name=availability]').forEach(x=>x.checked=false)"),'Comercializable No debe limpiar disponibilidad');
assert(css.includes('.form-modal fieldset[hidden]{display:none!important}'),'Los campos ocultos deben permanecer ocultos');
assert(css.includes('.form-modal [hidden]{display:none!important}'),'Los grupos dinámicos ocultos deben permanecer ocultos');
assert(css.includes('.calendar{display:block!important}.calendar[hidden]{display:none!important}'),'Móvil debe respetar la vista real');
console.log('Frontend 1.2.0: estructura, modos, sincronización y regresiones estáticas OK');

const manifest=JSON.parse(fs.readFileSync('google-apps-script/appsscript.json','utf8'));
assert.strictEqual(manifest.webapp?.executeAs,'USER_DEPLOYING','El Web App debe ejecutar como el propietario');
assert.strictEqual(manifest.webapp?.access,'ANYONE_ANONYMOUS','El calendario público debe conservar su Web App público');
